### ISSUE TITLE
Éditeur/Type de données intervalle, point, liste/pouvoir choisir le séparateur à utiliser

### ISSUE THREAD

**Issue by guybonin-scolab** [ljosa/issues-with-attachments#1]
**Contexte de la demande**

Au Québec francophone, on utilise souvent le point-virgule (;) pour séparer les éléments dans les couples (x, y) ou les intervalles [a, b]. Cela est particulièrement utile quand les nombre à séparer sont des nombres à virgules.

Présentement, si je dynamise en définissant un intervalle avec un point-virgule, la variable l'ignore et affiche quand même une virgule à la place. 
Exemple : 
![](https://screenshots.scolab.com/Public/Jing/MEB/q_1C6D1B49.png)

**Demande**

Pouvoir afficher le séparateur de notre choix quand on définit une variable de type intervalle, point ou liste.

Ne plus remplacer le séparateur par une virgule si un le point-virgule est choisi.

Donc, si je définis la variable point comme (x ; y), je verrai (x ; y) mais si je définis l'intervalle [a, b], je verrai [a, b]

**Comment by ljosa** [comment]
I think you must have meant to post this issue to a different project.
